### ISSUE TITLE
Regarding HYDRA for filter pruning

### ISSUE THREAD

**Issue by zjysteven** [inspire-group/compactness-robustness#1]
Hi,

Thanks for making the code public! I'm wondering if you plan to further make the code for Appendix C.9 (the structured pruning) public? If that's not the case, can you elaborate on what adaptation should be taken care of when applying HYDRA to pruning filters? (e.g., how to initialize the importance score for each filter?)

Thanks!

**Comment by VSehwag** [comment]
Hi, 

Currently, there is not much effort on supporting structured pruning, as it requires repurposing the whole repo and deviating from the key focus of the paper, i.e., unstructured pruning. I'll try to set it up once I have some bandwidth. 

Our approach to structured pruning is similar to unstructured pruning. Here we use the [Li et al.](https://arxiv.org/pdf/1608.08710.pdf) filter pruning technique as a baseline. In HYDRA, we use the proposed initialization of scores, and again pruned filters with the smallest L1 magnitudes of scores. We didn't investigate structured pruning further, but I believe there is certainly room for improvement here i.e, updating pruning criterion based on scores and the initialization itself.  

-Vikash

**Comment by zjysteven** [comment]
I see. Thanks for the details!
