### ISSUE TITLE
 cannot reach 57.2 on the cifar10 dataset int the pretraining

### ISSUE THREAD

**Issue by MVPR-Group** [inspire-group/compactness-robustness#5]
Hello, thank you for sharing the code, but I use "wrn_28_4"  network architecture on cifar10 dataset in the pretraining . The network architecture cannot reach 57.2 on the cifar10 dataset (I only reached 51.5 on the cifar10 dataset). Do you use tinyimages dataset in the pretraining? Thank you for your apply.

**Comment by VSehwag** [comment]
Yes, we do use additional real training data from tinyimages, as commonly done in the literature.
